### ISSUE TITLE
RangeError: Invalid Key Length

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#35] opened 2024-06-05 01:37 UTC
Hey there, I've got the following error, which persists after running a logout/cache clear. Seems to have just popped up this evening, I was able to watch last night. This issue happens in both the WebUI and via the XML/M3U links:

```
/mlbserver/node_modules/request-promise-core/lib/plumbing.js:130
            throw thrownException;
            ^
RangeError: Invalid key length
    at Decipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
    at Decipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
    at new Decipheriv (node:internal/crypto/cipher:289:3)
    at Object.createDecipheriv (node:crypto:146:10)
    at /mlbserver/index.js:943:27
    at /mlbserver/index.js:417:5
    at Request._rp_callbackOrig (/mlbserver/index.js:451:7)
    at Request.plumbing.callback (/mlbserver/node_modules/request-promise-core/lib/plumbing.js:76:39)
    at Request.RP$callback [as _callback] (/mlbserver/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/mlbserver/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/mlbserver/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/mlbserver/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_CRYPTO_INVALID_KEYLEN'
}
Version 2024.05.27
6/4/2024, 6:32:50 PM mlbserver started at http://192.168.208.15:9999
```

**Comment by tonywagner** [comment] 2024-06-05 02:22
Are you using a VPN?

**Comment by ahughes03** [comment] 2024-06-05 02:53
I use a Smart DNS service for my mlbserver docker container.

**Comment by tonywagner** [comment] 2024-06-05 03:06
I am guessing that is the cause.

I am closing this issue. If you can recreate the problem after disabling your smart DNS and clearing your session/cache, then you can open it again.

**Closed by tonywagner** 2024-06-05 03:06 UTC
